---
title: "ngsgenotype_snp"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Detect, load and clean files and genotypes:
```{r}
# Load libraries:
library(tidyverse)
library(ShortRead)
library(wesanderson)
source("genotyping_functions.r")

# Load all samples and mark controls and duplicates: # some negatives and positives are summarized if they are named the same(?)
allGenotypes <- ParseGenotypes(genotypePath = "Genotyped_SNPs/")

# Remove duplicates and controls:
allGenotypes <- allGenotypes[allGenotypes$Status != "Duplicated", ] # no duplicated names are allowed past this point
allGenotypes <- allGenotypes[allGenotypes$Status != "Control", ] # no controls are allowed past this point

# Separate autosomal genotypes and sexual genotypes if there are no repeated names:
if(!any(duplicated(allGenotypes$Sample))) {
  sexString <- "X-*|Y-*"
  autoGenotypes <- allGenotypes[, !grepl(sexString, colnames(allGenotypes))]
  saveRDS(autoGenotypes, file = "autoGenotypes.rds")
  sexGenotypes <- cbind(Sample = allGenotypes$Sample, allGenotypes[, grepl(sexString, colnames(allGenotypes))])
  saveRDS(sexGenotypes, file = "sexGenotypes.rds")
} else {
  cat("Error: allGenotypes contains repeated sample names.")
}
```

# Filter/QC samples and loci:
```{r}
# Mark samples based on quality:
QCGenotypes <- QCMarking(autoGenotypes, minPresent = 75, targetStatus = c("Loaded"), newStatus = "High Quality") %>%
  QCMarking(minPresent = 67, maxPresent = 74, targetStatus = c("Loaded"), newStatus = "Medium Quality") %>%
  QCMarking(minPresent = 24, maxPresent = 66, targetStatus = c("Loaded"), newStatus = "Low Quality") %>%
  QCMarking(minPresent = 00, maxPresent = 23, targetStatus = c("Loaded"), newStatus = "Fail Quality") # perhaps use a more comprehensive function and collapse this into one line

# Quick overview of quality of samples:
table(QCGenotypes$Status)
```

# Cluster all working samples (>= 67 working loci) and identify samples/clusters to be removed:
```{r}
library(allelematch)

# Make new object:
processedGenotypes <- QCGenotypes

# Cluster all samples with sufficient quality:
loadedDataAll <- LoadAMData(processedGenotypes, targetStatus = c("Medium Quality", "High Quality")) # Load all samples with 67 or more working loci

{png(file="amUniqueProfile_plot_All.png", width = 689, height = 425)
amProfileAll <- allelematch::amUniqueProfile(amDatasetFocal = loadedDataAll$Data, multilocusMap = loadedDataAll$AlleleKey, doPlot = TRUE, alleleMismatch = c(0:45))
dev.off()
saveRDS(amProfileAll, file = "amProfileAll.rds")
mmCutoff <- amProfileAll$alleleMismatch[amProfileAll$guessOptimum]}

uniqueBearsAll <- allelematch::amUnique(loadedDataAll$Data, multilocusMap = loadedDataAll$AlleleKey, alleleMismatch = mmCutoff)
allelematch::summary.amUnique(object = uniqueBearsAll, html = paste0("unique_bears_all_", mmCutoff, "_v1.html"))
allelematch::summary.amUnique(object = uniqueBearsAll, csv = paste0("unique_bears_all_", mmCutoff, "_v1.csv"))

# get clusters and high quality individuals:
clustersAll <- lapply(uniqueBearsAll$pairwise, function(x) {x$match$index})
samples75 <- processedGenotypes$Sample[processedGenotypes$Status == "High Quality"] # should this be placed after marking unclassified/multiplematched? To avoid to not keep orphans by mistake?

# check each one and see if they contain any matched sample from '75' run, note all samples in any who doesn't
GetOrphans <- function(hiqSamples, allClusters) {
  rmSamples <- c()
  for(curCluster in allClusters) {
    if(!any(curCluster %in% hiqSamples)) {
      rmSamples <- c(rmSamples, curCluster)
    }
  }
  return(unique(c(rmSamples, "0_EMPTY_NAME"))) # return orphaned samples
}

# Mark unclassified and multiplematched samples from all run:
processedGenotypes$Status[processedGenotypes$Sample %in% uniqueBearsAll$unclassified$index] <- "Unclassified"
processedGenotypes$Status[processedGenotypes$Sample %in% uniqueBearsAll$multipleMatches$index] <- "MultipleMatched"

# Get orphaned samples and mark them:
print(length(GetOrphans(hiqSamples = samples75, allClusters = clustersAll))) # number of newly added samples to be removed
processedGenotypes$Status[processedGenotypes$Sample %in% GetOrphans(samples75, clustersAll)] <- "Orphan"
```

# Recluster without samples chosen to be removed:
```{r}
# Make new object:
finalGenotypes <- processedGenotypes

# Rerun analysis without noted samples:
loadedDataFilt <- LoadAMData(finalGenotypes, targetStatus = c("Medium Quality", "High Quality")) # Load all samples with 67 or more working loci
uniqueBearsFilt <- allelematch::amUnique(loadedDataFilt$Data, multilocusMap = loadedDataFilt$AlleleKey, alleleMismatch = mmCutoff) # use stringent 10

# Save results as report as well as csv-file:
allelematch::summary.amUnique(object = uniqueBearsFilt, html = paste0("unique_bears_filt_", mmCutoff, "_v1.html"))
allelematch::summary.amUnique(object = uniqueBearsFilt, csv = paste0("unique_bears_filt_", mmCutoff, "_v1.csv"))

# Check if there are orphans still:
print(GetOrphans(hiqSamples = samples75, allClusters = lapply(uniqueBearsFilt$pairwise, function(x) {x$match$index}))) # make sure that there are no orphans

# Quick overview of statuses of samples:
table(finalGenotypes$Status)
```

# Calculate sex and generate statistics output: (remove?)
```{r}
sexGenotypes$Status <- finalGenotypes$Status[match(sexGenotypes$Sample, finalGenotypes$Sample)]
sexDetClusters <- sexGenotypes[sexGenotypes$Status %in% c("Medium Quality", "High Quality"),]
sexDetClusters$Cluster <- bearsFiltResult$uniqueIndex[match(sexDetClusters$Sample, bearsFiltResult$matchIndex)]

SexChooser <- function(clusterName, inputDF, minimumX = 1, minimumY = 3) {
  curMarkers <- inputDF[inputDF$Cluster == clusterName, ]
  curMarkers[rowSums(curMarkers[grep("^X", colnames(curMarkers))] == "") == 3, ] <- "" #rep("", ncol(curMarkers))
  presentX <- any(rowSums(curMarkers[grep("^X", colnames(curMarkers))] != "") >= minimumX)
  presentY <- any(rowSums(curMarkers[grep("^Y", colnames(curMarkers))] != "") >= minimumY)
  if(presentY) {
    SNPSex <- "Hane"
  } else if(presentX) {
    SNPSex <- "Hona"
  } else {
    SNPSex <- "Obestämd"
  }
  return(data.frame(Cluster = clusterName, SNP_sex = SNPSex))
}

bearSexList <- lapply(unique(sexDetClusters$Cluster), SexChooser, sexDetClusters, minimumX = 1, minimumY = 3) # minimum 1 X to get determined, minimum 3 Y to be a male
bearSexSummary <- do.call(rbind, bearSexList)
sexDetClusters$SNP_Sex <- bearSexSummary$SNP_sex[match(sexDetClusters$Cluster, bearSexSummary$Cluster)]
table(sexDetClusters$SNP_Sex) # summarise sex of samples
statisticsOutFile <- cbind(sexDetClusters[, -c(8)], QCGenotypes[match(sexDetClusters$Sample, QCGenotypes$Sample), -c(1, 2)]) 
writexl::write_xlsx(x = statisticsOutFile, path = "clustered_bear_samples_id_sex_genotypes_v1.xlsx")
```

# Rovbase input functions:
```{r}
SexChooser <- function(clusterName, martinDF, minimumX = 1, minimumY = 3) {
  curMarkers <- martinDF[martinDF$Cluster == clusterName, ]
  curMarkers[rowSums(curMarkers[grep("^X", colnames(curMarkers))] == "") == 3, ] <- "" # set all columns to nothing in case no X markers are present
  presentX <- any(rowSums(curMarkers[grep("^X", colnames(curMarkers))] != "") >= minimumX)
  presentY <- any(rowSums(curMarkers[grep("^Y", colnames(curMarkers))] != "") >= minimumY)
  if(presentY) {
    SNPSex <- "Hane"
  } else if(presentX) {
    SNPSex <- "Hona"
  } else {
    SNPSex <- "Obestämd"
  }
  return(data.frame(Cluster = clusterName, SNP_sex = SNPSex))
}

DetermineID <- function(allClusters, outDF, bearSexMeta = sexedBearIDs, SSRDataBecky = SSRDatabase) {
  curClust <- allClusters[1]
  remClusters <- allClusters[-1]
  print(curClust)
  testCluster <- bearSexMeta$Sample[bearSexMeta$Cluster == curClust]
  testIds <- SSRDataBecky$individ[SSRDataBecky$index %in% testCluster] # try with one with several SSR samples
  if(length(testIds) == 1) { # if one name found
    outName <- testIds
  } else if(length(testIds > 1)) {
    if(length(unique(testIds)) == 1) { # if all names the same
      outName <- testIds[1]
    } else {
      outName <- "0_MULTIPLE_NAMES" # if cluster has multiple different SSR IDs
    }
  } else { # if the cluster had no SSR name (new or otherwise)
    outName <- "0_NO_NAME"
  }
  # Check if name is repeated, and if so handle:
  if(outName %in% outDF$ID[grepl("^BI|^NRM_", outDF$ID)]) { # if name exists already
    otherCluster <- outDF$Cluster[outDF$ID == outName]
    otherSize <- sum(bearSexMeta$Cluster %in% otherCluster, na.rm = TRUE)
    currSize <- sum(bearSexMeta$Cluster %in% curClust, na.rm = TRUE)
    if(currSize > otherSize) { # if current cluster has more samples
      outDF$ID[outDF$Cluster == otherCluster] <- "0_REPEATED_NAME" # name is kept for current and the other is changed
    } else {
      outName <- "0_REPEATED_NAME" # current cluster gets the new name since it is smaller
    }
  }
  # Check if to recurse or return final output:
  if(length(remClusters) > 0) {
    DetermineID(remClusters, rbind(outDF, data.frame(Cluster = curClust, ID = outName)), bearSexMeta = bearSexMeta)
  } else {
    return(rbind(outDF, data.frame(Cluster = curClust, ID = outName)))
  }
} # failed bears are not handled well by this, BEAR gets multiple names tag for some reason

SexChooserSample <- function(sampleName, allDataDF, minimumX = 1, minimumY = 3) {
  sampleRow <- allDataDF[allDataDF$Sample == sampleName, ]
  # sampleRow <- as.data.frame(sampleRow)
  # sampleRow[is.na(sampleRow)] <- ""
  # print(sampleRow)
  sampleRow[rowSums(sampleRow[grep("^X", colnames(sampleRow))] == "") == 3, ] <- ""  # set all columns to nothing in case no X markers are present
  presentX <- any(rowSums(sampleRow[grep("^X", colnames(sampleRow))] != "") >= minimumX)
  presentY <- any(rowSums(sampleRow[grep("^Y", colnames(sampleRow))] != "") >= minimumY)
  if(presentY) {
    SNPSex <- "Hane"
  } else if(presentX) {
    SNPSex <- "Hona"
  } else {
    SNPSex <- "Obestämd"
  }
  return(SNPSex)
}

GenerateLopnummer <- function(clusterNames, allData, startNumber, lansbokstav, yearYY, outDF = data.frame(), deadStartNumber) {
  # clusterName <- as.character(clusterNames[1])
  clusterName <- clusterNames[1]
  remClusters <- clusterNames[-1]
  curSamples <- allData$Sample[allData$ID_ref == clusterName]
  if(startsWith(unique(sexedBearIDs$ID_ref[sexedBearIDs$ID_ref == clusterName]), "BI")) {
    outDF <- rbind(outDF, data.frame(ID_ref = clusterName, Lopnummer = ""))
    newNumber <- startNumber
    newDeadNumber <- deadStartNumber
  } else {
    if(any(startsWith(curSamples, "M"))) {
      outDF <- rbind(outDF, data.frame(ID_ref = clusterName, Lopnummer = paste0("B", deadStartNumber, "+")))
      newNumber <- startNumber
      newDeadNumber <- deadStartNumber + 1
    } else {
      outDF <- rbind(outDF, data.frame(ID_ref = clusterName, Lopnummer = paste0(lansbokstav, yearYY, "-", startNumber)))
      newNumber <- startNumber + 1
      newDeadNumber <- deadStartNumber
    }
  }
  if(length(remClusters) > 0) {
    GenerateLopnummer(clusterNames = remClusters, allData = allData, startNumber = newNumber, lansbokstav = lansbokstav, yearYY = yearYY, outDF = outDF, deadStartNumber = newDeadNumber)
  } else {
    return(outDF)
  }
}
```